import { Province } from './types';

export const INITIAL_PROVINCES: Record<string, Province> = {
  // --- BRAZILIAN STATES ---
  'BR-SP': {
    id: 'BR-SP',
    name: 'São Paulo',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'urban',
    resources: { money: 50, steel: 35, oil: 10, food: 20 },
    buildings: { industrial: 2, refinery: 1, fortress: 1, logistics: 2 },
    armies: { infantry: 12, artillery: 6, tanks: 4 },
    connections: ['BR-PR', 'BR-MS', 'BR-MG'],
    coordinates: { x: 670, y: 310 },
    points: '640,290 710,290 740,320 700,340 640,340 620,310'
  },
  'BR-PR': {
    id: 'BR-PR',
    name: 'Paraná',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'jungle',
    hasRiver: true,
    resources: { money: 30, steel: 20, oil: 5, food: 35 },
    buildings: { industrial: 1, refinery: 0, fortress: 1, logistics: 2, hydroelectric: 1 },
    armies: { infantry: 15, artillery: 8, tanks: 3 },
    connections: ['BR-MS', 'BR-SP', 'BR-SC', 'PY-ALR', 'PY-CAN', 'PY-ITA'],
    coordinates: { x: 620, y: 380 },
    points: '590,350 660,350 670,390 620,410 580,390'
  },
  'BR-MS': {
    id: 'BR-MS',
    name: 'Mato Grosso do Sul',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'plains',
    hasRiver: true,
    onAquifer: true,
    resources: { money: 20, steel: 10, oil: 15, food: 40 },
    buildings: { industrial: 1, refinery: 1, fortress: 2, logistics: 1 },
    armies: { infantry: 18, artillery: 10, tanks: 5 },
    connections: ['BR-MT', 'BR-GO', 'BR-MG', 'BR-SP', 'BR-PR', 'PY-AMA', 'PY-CON', 'PY-CAN', 'PY-APY', 'PY-PHY'],
    coordinates: { x: 530, y: 280 },
    points: '490,230 570,230 590,310 540,340 480,290'
  },
  'BR-SC': {
    id: 'BR-SC',
    name: 'Santa Catarina',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'plains',
    resources: { money: 25, steel: 15, oil: 2, food: 25 },
    buildings: { industrial: 1, refinery: 0, fortress: 0, logistics: 1 },
    armies: { infantry: 8, artillery: 4, tanks: 1 },
    connections: ['BR-PR', 'BR-RS'],
    coordinates: { x: 630, y: 430 },
    points: '610,415 670,410 680,440 620,450'
  },
  'BR-RS': {
    id: 'BR-RS',
    name: 'Rio Grande do Sul',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'plains',
    hasRiver: true,
    resources: { money: 35, steel: 25, oil: 5, food: 45 },
    buildings: { industrial: 2, refinery: 0, fortress: 2, logistics: 2 },
    armies: { infantry: 20, artillery: 12, tanks: 6 },
    connections: ['BR-SC', 'PY-ITA', 'PY-MIS', 'PY-NEE'],
    coordinates: { x: 590, y: 490 },
    points: '560,450 630,450 640,510 580,530 540,490'
  },
  'BR-MG': {
    id: 'BR-MG',
    name: 'Minas Gerais',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'plains',
    resources: { money: 40, steel: 50, oil: 5, food: 30 },
    buildings: { industrial: 3, refinery: 0, fortress: 1, logistics: 1 },
    armies: { infantry: 10, artillery: 5, tanks: 2 },
    connections: ['BR-SP', 'BR-MS', 'BR-GO', 'BR-DF'],
    coordinates: { x: 700, y: 230 },
    points: '640,190 730,195 760,250 710,285 640,285'
  },
  'BR-GO': {
    id: 'BR-GO',
    name: 'Goiás',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'plains',
    resources: { money: 15, steel: 10, oil: 2, food: 30 },
    buildings: { industrial: 1, refinery: 0, fortress: 0, logistics: 1 },
    armies: { infantry: 6, artillery: 3, tanks: 1 },
    connections: ['BR-MT', 'BR-MS', 'BR-MG', 'BR-DF'],
    coordinates: { x: 590, y: 170 },
    points: '550,130 620,130 630,190 570,225'
  },
  'BR-DF': {
    id: 'BR-DF',
    name: 'Distrito Federal',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'urban',
    resources: { money: 80, steel: 5, oil: 0, food: 5 },
    buildings: { industrial: 1, refinery: 0, fortress: 3, logistics: 3, airbase: 1 },
    armies: { infantry: 15, artillery: 10, tanks: 4 },
    connections: ['BR-GO', 'BR-MG'],
    coordinates: { x: 615, y: 155 },
    points: '600,140 630,140 630,170 600,170'
  },
  'BR-MT': {
    id: 'BR-MT',
    name: 'Mato Grosso',
    country: 'Brasil',
    controller: 'Brasil',
    terrain: 'jungle',
    onAquifer: true,
    resources: { money: 20, steel: 15, oil: 10, food: 60 },
    buildings: { industrial: 1, refinery: 0, fortress: 1, logistics: 1 },
    armies: { infantry: 10, artillery: 4, tanks: 2 },
    connections: ['BR-MS', 'BR-GO'],
    coordinates: { x: 470, y: 160 },
    points: '400,100 500,100 540,180 480,220 400,180'
  },

  // --- PARAGUAY DEPARTMENTS ---
  'PY-ASU': {
    id: 'PY-ASU',
    name: 'Asunción (Capital)',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'urban',
    hasRiver: true,
    resources: { money: 30, steel: 10, oil: 5, food: 10 },
    buildings: { industrial: 2, refinery: 0, fortress: 3, logistics: 3, airbase: 1 },
    armies: { infantry: 25, artillery: 15, tanks: 8 },
    connections: ['PY-CEN'],
    coordinates: { x: 330, y: 380 },
    points: '320,370 340,370 340,390 320,390'
  },
  'PY-PHY': {
    id: 'PY-PHY',
    name: 'Presidente Hayes',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'chaco',
    hasRiver: true,
    resources: { money: 10, steel: 5, oil: 8, food: 20 },
    buildings: { industrial: 1, refinery: 0, fortress: 1, logistics: 1 },
    armies: { infantry: 14, artillery: 6, tanks: 4 },
    connections: ['PY-CON', 'PY-SAP', 'PY-CEN', 'PY-NEE', 'PY-BOQ', 'PY-APY', 'BR-MS'],
    coordinates: { x: 270, y: 310 },
    points: '200,260 280,260 300,310 270,350 210,310'
  },
  'PY-ALR': {
    id: 'PY-ALR',
    name: 'Alto Paraná',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'jungle',
    hasRiver: true,
    resources: { money: 20, steel: 15, oil: 5, food: 15 },
    buildings: { industrial: 1, refinery: 1, fortress: 1, logistics: 1 },
    armies: { infantry: 16, artillery: 8, tanks: 5 },
    connections: ['PY-CAN', 'PY-CAA', 'PY-ITA', 'BR-PR'],
    coordinates: { x: 420, y: 370 },
    points: '400,350 440,350 445,390 405,390'
  },
  'PY-AMA': {
    id: 'PY-AMA',
    name: 'Amambay',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'jungle',
    resources: { money: 10, steel: 5, oil: 5, food: 15 },
    buildings: { industrial: 0, refinery: 0, fortress: 2, logistics: 1 },
    armies: { infantry: 18, artillery: 10, tanks: 6 },
    connections: ['PY-CON', 'PY-CAN', 'PY-SAP', 'BR-MS'],
    coordinates: { x: 400, y: 260 },
    points: '370,240 430,240 430,280 370,280'
  },
  'PY-CON': {
    id: 'PY-CON',
    name: 'Concepción',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'plains',
    hasRiver: true,
    resources: { money: 10, steel: 8, oil: 5, food: 15 },
    buildings: { industrial: 1, refinery: 0, fortress: 1, logistics: 1 },
    armies: { infantry: 15, artillery: 6, tanks: 3 },
    connections: ['PY-AMA', 'PY-PHY', 'PY-SAP', 'BR-MS'],
    coordinates: { x: 330, y: 240 },
    points: '300,210 360,210 360,260 300,260'
  },
  'PY-CAN': {
    id: 'PY-CAN',
    name: 'Canindeyú',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'jungle',
    resources: { money: 10, steel: 5, oil: 5, food: 25 },
    buildings: { industrial: 0, refinery: 0, fortress: 2, logistics: 1 },
    armies: { infantry: 15, artillery: 7, tanks: 4 },
    connections: ['PY-AMA', 'PY-ALR', 'PY-CAA', 'PY-SAP', 'BR-MS', 'BR-PR'],
    coordinates: { x: 430, y: 310 },
    points: '400,290 450,290 445,335 395,335'
  },
  'PY-BOQ': {
    id: 'PY-BOQ',
    name: 'Boquerón',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'chaco',
    resources: { money: 10, steel: 5, oil: 25, food: 10 },
    buildings: { industrial: 0, refinery: 2, fortress: 1, logistics: 1 },
    armies: { infantry: 12, artillery: 5, tanks: 3 },
    connections: ['PY-APY', 'PY-PHY'],
    coordinates: { x: 150, y: 220 },
    points: '90,160 170,160 190,250 110,250'
  },
  'PY-APY': {
    id: 'PY-APY',
    name: 'Alto Paraguay',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'chaco',
    resources: { money: 10, steel: 5, oil: 12, food: 15 },
    buildings: { industrial: 0, refinery: 1, fortress: 1, logistics: 1 },
    armies: { infantry: 10, artillery: 4, tanks: 2 },
    connections: ['PY-BOQ', 'PY-PHY', 'PY-CON', 'BR-MS'],
    coordinates: { x: 230, y: 160 },
    points: '160,100 250,100 270,190 190,200'
  },
  'PY-SAP': {
    id: 'PY-SAP',
    name: 'San Pedro',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'plains',
    onAquifer: true,
    resources: { money: 10, steel: 5, oil: 2, food: 35 },
    buildings: { industrial: 1, refinery: 0, fortress: 1, logistics: 2 },
    armies: { infantry: 12, artillery: 6, tanks: 2 },
    connections: ['PY-CON', 'PY-AMA', 'PY-CAN', 'PY-CAA', 'PY-CEN', 'PY-PHY'],
    coordinates: { x: 350, y: 310 },
    points: '310,290 380,290 380,335 310,335'
  },
  'PY-CAA': {
    id: 'PY-CAA',
    name: 'Caaguazú',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'plains',
    resources: { money: 12, steel: 10, oil: 2, food: 20 },
    buildings: { industrial: 1, refinery: 0, fortress: 1, logistics: 1 },
    armies: { infantry: 10, artillery: 5, tanks: 3 },
    connections: ['PY-SAP', 'PY-CAN', 'PY-ALR', 'PY-ITA', 'PY-CEN'],
    coordinates: { x: 390, y: 355 },
    points: '360,340 405,340 405,370 360,370'
  },
  'PY-ITA': {
    id: 'PY-ITA',
    name: 'Itapúa',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'plains',
    hasRiver: true,
    resources: { money: 15, steel: 15, oil: 5, food: 30 },
    buildings: { industrial: 1, refinery: 0, fortress: 2, logistics: 1 },
    armies: { infantry: 18, artillery: 8, tanks: 4 },
    connections: ['PY-ALR', 'PY-CAA', 'PY-MIS', 'PY-CEN', 'BR-PR', 'BR-RS'],
    coordinates: { x: 390, y: 440 },
    points: '360,420 420,410 430,460 370,470'
  },
  'PY-MIS': {
    id: 'PY-MIS',
    name: 'Misiones',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'plains',
    resources: { money: 8, steel: 5, oil: 2, food: 20 },
    buildings: { industrial: 0, refinery: 0, fortress: 1, logistics: 1 },
    armies: { infantry: 8, artillery: 4, tanks: 1 },
    connections: ['PY-ITA', 'PY-CEN', 'PY-NEE', 'BR-RS'],
    coordinates: { x: 315, y: 445 },
    points: '290,425 340,425 340,465 290,465'
  },
  'PY-NEE': {
    id: 'PY-NEE',
    name: 'Ñeembucú',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'plains',
    hasRiver: true,
    resources: { money: 8, steel: 2, oil: 5, food: 15 },
    buildings: { industrial: 0, refinery: 1, fortress: 1, logistics: 1 },
    armies: { infantry: 10, artillery: 4, tanks: 2 },
    connections: ['PY-MIS', 'PY-CEN', 'PY-PHY', 'BR-RS'],
    coordinates: { x: 250, y: 430 },
    points: '220,410 270,410 270,455 220,455'
  },
  'PY-CEN': {
    id: 'PY-CEN',
    name: 'Central',
    country: 'Paraguai',
    controller: 'Paraguai',
    terrain: 'urban',
    hasRiver: true,
    onAquifer: true,
    resources: { money: 20, steel: 10, oil: 2, food: 15 },
    buildings: { industrial: 1, refinery: 0, fortress: 2, logistics: 2 },
    armies: { infantry: 22, artillery: 10, tanks: 5 },
    connections: ['PY-SAP', 'PY-CAA', 'PY-ITA', 'PY-MIS', 'PY-NEE', 'PY-PHY', 'PY-ASU'],
    coordinates: { x: 305, y: 395 },
    points: '270,380 340,380 340,415 270,415'
  }
};
